# Generated by Django 2.2.2 on 2019-07-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailCarport',
            fields=[
                ('carport_site', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('owner_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carport',
            fields=[
                ('site', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('current_car_license', models.CharField(default='', max_length=200)),
                ('owner_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.IntegerField(db_column='Fld', primary_key=True, serialize=False)),
                ('carport_site', models.CharField(max_length=200)),
                ('car_license', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=200)),
                ('negotiate_site', models.CharField(max_length=200)),
                ('negotiate_list', models.CharField(max_length=1000)),
                ('record_time', models.DateTimeField()),
                ('status', models.CharField(default='underway', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_license', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('account', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('weekday', models.IntegerField()),
                ('group', models.IntegerField()),
                ('carport_site', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('remain', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_license', models.CharField(max_length=200)),
                ('carport_site', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField()),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('negotiate', '协商中'), ('success', '进行中'), ('warning', '已结束'), ('active', '已撤销'), ('danger', '超时'), ('invalid', '无效订单')], max_length=10)),
                ('carport_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='carport.User')),
                ('carport_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='carport.User')),
            ],
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.IntegerField(db_column='Fld', primary_key=True, serialize=False)),
                ('belong_phone', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', '进行中'), ('warning', '已接受'), ('active', '超时/已拒绝'), ('danger', '协商失败')], max_length=10)),
                ('negotiate_id', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='carport.Order')),
            ],
        ),
    ]
