# Generated by Django 2.2.2 on 2019-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='negotiate_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
