# Generated by Django 2.2.2 on 2019-07-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailCarport',
            fields=[
                ('carport_site', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
