# Generated by Django 2.2.2 on 2019-07-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carport',
            name='owner_phonex',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='carport_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='carport.User'),
        ),
    ]
