# Generated by Django 2.2.2 on 2019-06-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carport',
            old_name='user_id',
            new_name='user',
        ),
    ]
