# Generated by Django 2.2.2 on 2019-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='begin_hours',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='end_hours',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
