# Generated by Django 2.2.2 on 2019-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0002_auto_20190620_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='carport',
            name='locate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
