# Generated by Django 2.2.2 on 2019-07-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0002_inform_negotiate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
