# Generated by Django 2.2.2 on 2019-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0002_availcarport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.IntegerField(db_column='Fld', primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=200)),
                ('request_site', models.CharField(max_length=200)),
                ('request_list', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='carport',
            name='owner_phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
