# Generated by Django 2.2.2 on 2019-07-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0003_auto_20190724_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiation',
            old_name='negotiate_site',
            new_name='begin_site',
        ),
        migrations.RenameField(
            model_name='negotiation',
            old_name='owner_phone',
            new_name='last_site',
        ),
    ]
