# Generated by Django 2.2.2 on 2019-07-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0003_auto_20190714_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='status',
            field=models.CharField(choices=[('success', '进行中'), ('warning', '已回绝'), ('active', '超时'), ('danger', '协商失败')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('negotiate', '协商中'), ('success', '进行中'), ('warning', '已结束'), ('active', '已撤销'), ('danger', '超时')], max_length=10),
        ),
    ]
