# Generated by Django 2.2.2 on 2019-07-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0003_auto_20190703_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carport',
            new_name='carport_site',
        ),
    ]
