# Generated by Django 2.2.2 on 2019-07-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0004_auto_20190704_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='availcarport',
            name='owner_phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
